Create monitored directory if does not exist
pytroll/pytroll-collectors pull request #139
Opened 2023-05-22 11:09 UTC by tecnavia-dev

Create monitored directory, if does not exist

2023-05-23 07:15 UTC, mraspaud requested changes
Thanks for this PR. Could you write a small test for this?

2023-05-24 13:08 UTC, mraspaud reviewed
Thanks for adding this functionality, some comments inline

2023-05-24 13:08 UTC, mraspaud commented on pytroll_collectors/trollstalker.py
> +        # Create directory, if it does not exist
This comment is not needed...

2023-05-24 14:10 UTC, tecnavia-dev commented on pytroll_collectors/trollstalker.py
> +        # Create directory, if it does not exist
Ok

2023-05-24 14:15 UTC, tecnavia-dev commented on pytroll_collectors/trollstalker.py
> +        raise
I don't think, we need it.
I can move it, so It'll be cleaner.

2023-07-06 09:41 UTC, tecnavia-dev commented
Do we need to make any further changes?

2023-07-06 11:55 UTC, mraspaud approved these changes
LGTM

2023-07-06 11:55 UTC, merged